a = input("Enter first element ")
b = input("Enter second element ")

print("Relation operation on array")
print("Result of a>b")
print(a>b)
print("Result of a>=b")
print(a>=b)
print("Result of a<=b")
print(a<=b)
print("Result of a==b")
print(a==b)
print("Result of a!=b")
print(a!=b)